### ISSUE TITLE
Project unmaintained

### ISSUE THREAD

**Issue by oteoe** [testing-library/preact-hooks-testing-library#19]
@nickmccurdy 
@CarsonMcKinstry 
@aduth 
@fbring 

is this library dead/unmaintained?

As far as I can see there is renderHook in the newer version of preact-testing-library

is this one still needed?

**Comment by nickserv** [comment]
Not all our repositories have active maintainers, but organization maintainers (myself included) will occasionally review them.

As for whether we still need this package, let's continue the discussion in #17.
